### ISSUE TITLE
Overloading animate in UIView make the compiler unable to resolve things

### ISSUE THREAD

**Issue by gsabran** [PromiseKit/UIKit#2]
Xcode is not able to distinguish between the built in animate, and the one from PromiseKit, and fails to compile (see http://stackoverflow.com/questions/39397967/ambiguous-use-of-animatewithdurationdelayoptionsanimations) This is very annoying.

**Comment by mxcl** [comment]
This only started happening since Swift 3, since the completion parameter now has a default argument, where before it did not.

Hard to detect such things without bug reports, sorry for your inconvenience.

**Comment by gsabran** [comment]
Sure, no problem. Yeah it started with swift 3 / Xcode 8 GM

**Comment by gsabran** [comment]
Excellent, thanks
