### ISSUE TITLE
iTunes Connect rejects builds because NSPhotoLibraryUsageDescription is required

### ISSUE THREAD

**Issue by robbiet480** [PromiseKit/UIKit#3]
Hey,

I tried submitting a few builds today. They were all rejected with the following error (which I received in my email):

`This app attempts to access privacy-sensitive data without a usage description. The app's Info.plist must contain an NSPhotoLibraryUsageDescription key with a string value explaining to the user how the app uses this data.`

I identified PromiseKit as the only library with any mention of Photo or `UIImagePicker` (`UIImagePicker` can cause a reject, see [this](https://forums.developer.apple.com/thread/62229)).

As I didn't use PromiseKit for anything relating to UI I removed:
- `UIViewController+AnyPromise.m`
- `UIViewController+AnyPromise.h`
- `UIViewController+Promise.swift`

After removing those files my builds are being accepted fine.

What would the long term fix for this be?

**Comment by mxcl** [comment]
I'm thinking the UIKit subspec will need another subspec for `UIImagePickerController`.

Carthage users will have to deal with it manually for now.

**Comment by robbiet480** [comment]
I attempted to submit a build with the latest changes but it failed. @mxcl is still looking for a solution. This issue should be reopened.

**Comment by mxcl** [comment]
I moved the subspec to root level so it won't get included by default now. It seems strange that it was getting included by default, since there is then no way _not_ to include it. I figure it may be a bug since when I tested locally (with the `path:` syntax) it did work as expected.

Whatever, it should now work.

**Comment by mxcl** [comment]
Pushing the 4.0.2 pod is pending: https://github.com/CocoaPods/CocoaPods/issues/5880
