### ISSUE TITLE
UIImagePickerController+Promise.swift not in pod 4.0

### ISSUE THREAD

**Issue by zhiyanshao** [PromiseKit/UIKit#4]
Currently my pod file looks like the following and UIImagePickerController+Promise.swift is not included in UIKit. Is there a way to include it through pod?

    pod 'PromiseKit/CoreLocation', '~> 4.0'
    pod 'PromiseKit/MapKit', '~> 4.0'
    pod 'PromiseKit/MessageUI', '~> 4.0'
    pod 'PromiseKit/UIKit', '~> 4.0'

**Comment by mxcl** [comment]
We had to remove this, see #3.

However we probably should update the docs, you can still get this, it's just a separate pod:

https://github.com/mxcl/PromiseKit/blob/master/PromiseKit.podspec#L186

**Comment by zhiyanshao** [comment]
I see. The following worked for me. Thanks a lot!

pod 'PromiseKit/UIImagePickerController', '~> 4.0'

**Comment by mxcl** [comment]
Reopening as we should update the docs.
