### ISSUE TITLE
Having trouble importing PMKUIKit

### ISSUE THREAD

**Issue by warpling** [PromiseKit/UIKit#5]
I'm having trouble on both release version `4.1.7` and `5.0.0-beta8` importing `PMKUIKit` into an Objective-C project. I consistently get "Module 'PMKUIKit' not found.

I was previously using the Swift 2.3 compatible branches before recently migrating to the new versions and import syntax:
```
@import PromiseKit;
@import PMKUIKit;
```

I've trashed derived data, clean built, rebuilt pods, etc.

**Comment by warpling** [comment]
FWIW, my podfile looks something like this:
```
# Uncomment this line to define a global platform for your project
platform :ios, '8.3'

# ignore all warnings from all pods
inhibit_all_warnings!

source 'https://github.com/CocoaPods/Specs.git'

target 'Foo' do
    # Use Swift Frameworks
    swift_version = "3.0"
    use_frameworks!

    pod 'PromiseKit', :git => 'https://github.com/mxcl/PromiseKit.git'
    pod 'PromiseKit/UIKit', :git => 'https://github.com/mxcl/PromiseKit.git'

    post_install do |installer|
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings['SWIFT_VERSION'] = '3.0'
        end
    end
end
```

**Comment by warpling** [comment]
Turns out `@import PMKUIKit;` is wholly unnecessary in Objective-C with the latest `4.1.7` release!

**Comment by mxcl** [comment]
You only have to import PMKUIKit with Carthage. Cocoapods includes it automatically. The differences are due to limitations in Carthage
