### ISSUE TITLE
Multiple dependencies with different sources for `PromiseKit`

### ISSUE THREAD

**Issue by besi** [PromiseKit/UIKit#7]
I get an error while installing `UIKit` in my project.

```Gemfile

  # ...
platform :ios, '9.0'
use_frameworks!

target 'MyApp' do
  swift_version = '4.0'
  # ...
  pod 'PromiseKit', git: 'https://github.com/mxcl/PromiseKit', branch: 'master' #, '~> 4.3.2'
  pod 'PromiseKit/UIKit', '~> 4.0'
end
```

I get this error:

> [!] There are multiple dependencies with different sources for `PromiseKit` in `Podfile`:
> 
> - PromiseKit (from `https://github.com/mxcl/PromiseKit`, branch `master`)
> - PromiseKit/UIKit (~> 4.0)

**Comment by besi** [comment]
It looks like this is a problem with cocoapods, I did file an issue there:
https://github.com/CocoaPods/CocoaPods/issues/7097

**Comment by mxcl** [comment]
You can do:

```
pod 'PromiseKit',
    git: 'https://github.com/mxcl/PromiseKit', branch: 'master',
    subspecs: ['Foundation', 'UIKit']
```

As a workaround.

**Comment by mxcl** [comment]
There are no outstanding changes to PromiseKit, so probably you don't need to refer to the git branch anymore.
